# Generated by Django 5.2.6 on 2025-10-26 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='ชื่อไฟล์ backup พร้อม version และ timestamp', max_length=255, verbose_name='ชื่อไฟล์')),
                ('environment', models.CharField(choices=[('local', 'Local'), ('production', 'Production')], help_text='Local หรือ Production', max_length=20, verbose_name='Environment')),
                ('file_size', models.BigIntegerField(default=0, help_text='ขนาดไฟล์เป็น bytes', verbose_name='ขนาดไฟล์')),
                ('postgresql_version', models.CharField(blank=True, help_text='เวอร์ชัน PostgreSQL', max_length=20, null=True, verbose_name='PostgreSQL Version')),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', help_text='Manual หรือ Scheduled', max_length=20, verbose_name='ประเภท Backup')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', help_text='สถานะการ backup', max_length=20, verbose_name='สถานะ')),
                ('progress', models.PositiveIntegerField(default=0, help_text='เปอร์เซ็นต์ความคืบหน้า (0-100)', verbose_name='ความคืบหน้า')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('notes', models.TextField(blank=True, help_text='หมายเหตุเพิ่มเติม', null=True, verbose_name='หมายเหตุ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
            ],
            options={
                'verbose_name': 'ประวัติการ Backup',
                'verbose_name_plural': 'ประวัติการ Backup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ชื่อสำหรับ schedule นี้', max_length=100, verbose_name='ชื่อ Schedule')),
                ('environment', models.CharField(choices=[('local', 'Local'), ('production', 'Production')], help_text='Local หรือ Production', max_length=20, verbose_name='Environment')),
                ('schedule_type', models.CharField(choices=[('daily', 'ทุกวัน'), ('weekly', 'ทุกสัปดาห์'), ('monthly', 'ทุกเดือน')], default='daily', help_text='ความถี่ในการ backup', max_length=20, verbose_name='ประเภท Schedule')),
                ('time', models.TimeField(help_text='เวลาที่ต้องการ backup (เวลาไทย)', verbose_name='เวลา')),
                ('is_active', models.BooleanField(default=True, help_text='เปิด/ปิดใช้งาน schedule นี้', verbose_name='เปิดใช้งาน')),
                ('last_run', models.DateTimeField(blank=True, help_text='วันเวลาที่ backup ครั้งล่าสุด', null=True, verbose_name='รันครั้งล่าสุด')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
            ],
            options={
                'verbose_name': 'ตารางการ Backup',
                'verbose_name_plural': 'ตารางการ Backup',
                'ordering': ['name'],
            },
        ),
    ]
