# Generated by Django 5.2.6 on 2025-10-25 12:21

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='อัปโหลดรูปโปรไฟล์ของคุณ', null=True, upload_to=accounts.models.user_avatar_upload_path, verbose_name='รูปโปรไฟล์')),
                ('phone_number', models.CharField(blank=True, help_text='เบอร์โทรศัพท์ติดต่อ', max_length=20, null=True, verbose_name='เบอร์โทรศัพท์')),
                ('bio', models.TextField(blank=True, help_text='ข้อมูลเพิ่มเติมเกี่ยวกับคุณ', max_length=500, null=True, verbose_name='ข้อมูลส่วนตัว')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='วันเกิด')),
                ('address', models.TextField(blank=True, max_length=500, null=True, verbose_name='ที่อยู่')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_profiles', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แก้ไข')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'โปรไฟล์ผู้ใช้',
                'verbose_name_plural': 'โปรไฟล์ผู้ใช้',
                'ordering': ['-created_at'],
            },
        ),
    ]
