# Generated by Django 5.2.6 on 2025-10-26 12:31

import django.db.models.deletion
import django_summernote.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Defaults to filename, if left blank', max_length=255, null=True)),
                ('file', models.FileField(upload_to=django_summernote.utils.uploaded_filepath)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ไฟล์แนบคู่มือ',
                'verbose_name_plural': 'ไฟล์แนบคู่มือ',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ManualCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ชื่อหมวดหมู่คู่มือการใช้งาน', max_length=100, unique=True, verbose_name='ชื่อหมวดหมู่')),
                ('slug', models.CharField(blank=True, help_text='URL-friendly version of the name (auto-generated or manual)', max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='รายละเอียดเพิ่มเติมเกี่ยวกับหมวดหมู่', null=True, verbose_name='รายละเอียด')),
                ('icon', models.CharField(blank=True, help_text="Font Awesome class เช่น 'fas fa-book'", max_length=50, verbose_name='ไอคอน')),
                ('order', models.IntegerField(default=0, help_text='ลำดับการแสดงผล (น้อยกว่า = แสดงก่อน)', verbose_name='ลำดับ')),
                ('is_active', models.BooleanField(default=True, help_text='สถานะการใช้งานของหมวดหมู่', verbose_name='ใช้งานได้')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_manual_categories', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_manual_categories', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แก้ไข')),
            ],
            options={
                'verbose_name': 'หมวดหมู่คู่มือ',
                'verbose_name_plural': 'หมวดหมู่คู่มือ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='ชื่อคู่มือการใช้งาน', max_length=200, verbose_name='ชื่อคู่มือ')),
                ('slug', models.CharField(blank=True, help_text='URL-friendly version of the title (auto-generated or manual)', max_length=255, unique=True, verbose_name='Slug')),
                ('content', models.TextField(help_text='เนื้อหาคู่มือการใช้งาน (ใช้ Summernote Editor)', verbose_name='รายละเอียด')),
                ('is_public', models.BooleanField(default=False, help_text='แสดงสำหรับทุกคน', verbose_name='สาธารณะ')),
                ('seo_title', models.CharField(blank=True, help_text='ชื่อหน้าเว็บสำหรับ SEO (แนะนำไม่เกิน 100 ตัวอักษร)', max_length=100, null=True, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, help_text='คำอธิบายสำหรับ SEO (แนะนำไม่เกิน 200 ตัวอักษร)', null=True, verbose_name='SEO Description')),
                ('is_active', models.BooleanField(default=True, help_text='สถานะการใช้งานของคู่มือ', verbose_name='ใช้งานได้')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_manuals', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
                ('order_before', models.ForeignKey(blank=True, help_text='เลือกคู่มือที่จะอยู่ก่อนหน้านี้ หรือปล่อยว่างเพื่ออยู่ท้ายสุด', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_after', to='manuals.manual', verbose_name='อยู่ก่อน')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_manuals', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แก้ไข')),
                ('visible_to_groups', models.ManyToManyField(blank=True, help_text='เลือกกลุ่มที่สามารถเห็นคู่มือนี้', to='auth.group', verbose_name='แสดงสำหรับกลุ่ม')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuals', to='manuals.manualcategory', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'คู่มือการใช้งาน',
                'verbose_name_plural': 'คู่มือการใช้งาน',
                'ordering': ['category__order', 'category__name', 'title'],
            },
        ),
    ]
