# Generated by Django 5.2.6 on 2025-10-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manual',
            options={'ordering': ['category__order', 'category__name', 'order', 'title'], 'verbose_name': 'คู่มือการใช้งาน', 'verbose_name_plural': 'คู่มือการใช้งาน'},
        ),
        migrations.RemoveField(
            model_name='manual',
            name='order_before',
        ),
        migrations.AddField(
            model_name='manual',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='ลำดับการแสดงผล (ตัวเลขน้อย = แสดงก่อน)', verbose_name='ลำดับ'),
        ),
    ]
