# Generated by Django 5.2.6 on 2025-10-25 13:30

import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ชื่อหมวดหมู่สินค้า', max_length=100, unique=True, verbose_name='ชื่อหมวดหมู่')),
                ('description', models.TextField(blank=True, help_text='รายละเอียดเพิ่มเติมเกี่ยวกับหมวดหมู่สินค้า', max_length=500, null=True, verbose_name='รายละเอียดหมวดหมู่')),
                ('image', models.ImageField(blank=True, help_text='อัปโหลดรูปหมวดหมู่สินค้า (ขนาด 1:1)', null=True, upload_to=products.models.category_image_upload_path, verbose_name='รูปหมวดหมู่')),
                ('is_active', models.BooleanField(default=True, help_text='หมวดหมู่นี้ใช้งานได้หรือไม่', verbose_name='ใช้งานได้')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_categories', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แก้ไข')),
            ],
            options={
                'verbose_name': 'หมวดหมู่สินค้า',
                'verbose_name_plural': 'หมวดหมู่สินค้า',
                'ordering': ['name'],
            },
        ),
    ]
