# Generated by Django 5.2.6 on 2025-10-26 09:10

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alt_text',
            field=models.CharField(blank=True, help_text='ข้อความอธิบายรูปสำหรับผู้ใช้ที่มองไม่เห็น', max_length=100, null=True, verbose_name='Alt Text'),
        ),
        migrations.AddField(
            model_name='category',
            name='og_description',
            field=models.TextField(blank=True, help_text='คำอธิบายสำหรับแชร์ใน Social Media', max_length=160, null=True, verbose_name='OG Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='og_image',
            field=models.ImageField(blank=True, help_text='รูปสำหรับแชร์ใน Social Media (ขนาด 1200x630px)', null=True, upload_to=products.models.category_image_upload_path, verbose_name='OG Image'),
        ),
        migrations.AddField(
            model_name='category',
            name='og_title',
            field=models.CharField(blank=True, help_text='ชื่อสำหรับแชร์ใน Social Media', max_length=60, null=True, verbose_name='OG Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_description',
            field=models.TextField(blank=True, help_text='คำอธิบายสำหรับ SEO (แนะนำไม่เกิน 160 ตัวอักษร)', max_length=160, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, help_text='ชื่อหน้าเว็บสำหรับ SEO (แนะนำไม่เกิน 60 ตัวอักษร)', max_length=60, null=True, verbose_name='SEO Title'),
        ),
    ]
