# Generated by Django 5.2.6 on 2025-10-26 09:29

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_alt_text_category_og_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='og_description',
            field=models.TextField(blank=True, help_text='คำอธิบายสำหรับแชร์ใน Social Media', null=True, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='og_image',
            field=models.ImageField(blank=True, help_text='รูปสำหรับแชร์ใน Social Media (ขนาด 1200x630px - อัตราส่วน 16:9)', null=True, upload_to=products.models.category_image_upload_path, verbose_name='OG Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='og_title',
            field=models.CharField(blank=True, help_text='ชื่อสำหรับแชร์ใน Social Media', max_length=255, null=True, verbose_name='OG Title'),
        ),
    ]
