# Generated by Django 5.2.6 on 2025-10-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_og_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='og_description',
            field=models.TextField(blank=True, help_text='คำอธิบายสำหรับแชร์ใน Social Media (แนะนำไม่เกิน 200 ตัวอักษร เพื่อความเหมาะสมในทุกแพลตฟอร์ม)', null=True, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='og_title',
            field=models.CharField(blank=True, help_text='ชื่อสำหรับแชร์ใน Social Media (แนะนำไม่เกิน 100 ตัวอักษร เพื่อความเหมาะสมในทุกแพลตฟอร์ม)', max_length=100, null=True, verbose_name='OG Title'),
        ),
    ]
