# Generated by Django 5.2.6 on 2025-10-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_og_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='รายละเอียดเพิ่มเติมเกี่ยวกับหมวดหมู่สินค้า', null=True, verbose_name='รายละเอียดหมวดหมู่'),
        ),
    ]
