# Generated by Django 5.2.6 on 2025-10-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the name (auto-generated)', max_length=120, unique=True, verbose_name='Slug'),
        ),
    ]
