# Generated by Django 5.2.6 on 2025-10-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, help_text='URL-friendly version of the name (auto-generated or manual)', max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
