# Generated by Django 5.2.6 on 2025-10-26 11:16

import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ชื่อแบรนด์สินค้า', max_length=100, unique=True, verbose_name='ชื่อแบรนด์')),
                ('slug', models.CharField(blank=True, help_text='URL-friendly version of the name (auto-generated or manual)', max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='รายละเอียดเพิ่มเติมเกี่ยวกับแบรนด์', null=True, verbose_name='รายละเอียดแบรนด์')),
                ('logo', models.ImageField(blank=True, help_text='อัปโหลดโลโก้แบรนด์ (อัตราส่วน 1:1)', null=True, upload_to=products.models.brand_logo_upload_path, verbose_name='Logo แบรนด์')),
                ('alt_text', models.CharField(blank=True, help_text='ข้อความอธิบายโลโก้สำหรับผู้ใช้ที่มองไม่เห็น', max_length=100, null=True, verbose_name='Alt Text')),
                ('seo_title', models.CharField(blank=True, help_text='ชื่อหน้าเว็บสำหรับ SEO (แนะนำไม่เกิน 100 ตัวอักษร)', max_length=100, null=True, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, help_text='คำอธิบายสำหรับ SEO (แนะนำไม่เกิน 200 ตัวอักษร)', null=True, verbose_name='SEO Description')),
                ('og_image', models.ImageField(blank=True, help_text='รูปสำหรับแชร์ใน Social Media (ขนาด 1200x630px - อัตราส่วน 16:9)', null=True, upload_to=products.models.brand_logo_upload_path, verbose_name='OG Image')),
                ('og_title', models.CharField(blank=True, help_text='ชื่อสำหรับแชร์ใน Social Media (แนะนำไม่เกิน 100 ตัวอักษร)', max_length=100, null=True, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, help_text='คำอธิบายสำหรับแชร์ใน Social Media (แนะนำไม่เกิน 200 ตัวอักษร)', null=True, verbose_name='OG Description')),
                ('is_active', models.BooleanField(default=True, help_text='สถานะการใช้งานของแบรนด์', verbose_name='ใช้งานได้')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_brands', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_brands', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แก้ไข')),
            ],
            options={
                'verbose_name': 'แบรนด์',
                'verbose_name_plural': 'แบรนด์',
                'ordering': ['name'],
            },
        ),
    ]
